# 開発環境用ログ設定
# ========================================
# 開発・デバッグ用の詳細ログ設定
# 本番環境では config.yaml を使用

# 継承元設定（必要最小限のみ記載、他は config.yaml から継承）
server:
  port: 8000

# 開発環境専用ログ設定
logging:
  # 開発環境でのログレベル設定
  level: "DEBUG"                      # 開発環境では DEBUG レベルを有効
  enable_file_output: true            # ファイル出力を有効にするか
  log_dir: "logs"                     # ログディレクトリ
  max_file_size_mb: 20                # 開発環境では小さめの20MB
  backup_count: 2                     # バックアップファイル数（開発は少なめ）
  enable_console_output: true         # コンソール出力を有効にするか
  console_level: "DEBUG"              # コンソール出力のログレベル（DEBUGまで）
  file_level: "DEBUG"                 # ファイル出力のログレベル（DEBUGまで）
  
  # 開発環境では頻繁なログ抑制は無効
  suppress_frequent_logs: false       # 開発時は全ログを出力
  frame_log_interval: 10              # フレーム処理ログの間隔（秒、短め）
  detection_log_sampling: 5           # 検出ログのサンプリング（5フレームに1回）
  max_duplicate_suppression: 3        # 重複ログの最大抑制回数（短め）
  
  # 開発専用ログ機能
  verbose_detection_logs: true        # 詳細な検出ログを有効にする
  performance_timing_logs: true       # パフォーマンス計測ログを有効にする
  websocket_debug_logs: true          # WebSocketデバッグログを有効にする 