# CI環境用テスト設定
# ========================================
# CI環境（自動テスト）用の最小限設定
# 単体テスト・統合テストで使用

server:
  port: 8888  # テスト用の異なるポート番号

logging:
  level: "ERROR"                    # CIではエラーのみログ出力
  enable_file_output: false         # CIではファイル出力無効
  enable_console_output: true       # コンソール出力は有効
  console_level: "ERROR"            # エラーレベルのみ出力
  suppress_frequent_logs: true      # 繰り返しログは抑制

detector:
  use_mediapipe: false              # テスト時はMediaPipe無効
  use_yolo: false                   # テスト時はYOLO無効
  
# テスト用の閾値設定
conditions:
  absence:
    threshold_seconds: 10
  smartphone_usage:
    threshold_seconds: 5

# テスト時は各種外部連携を無効化
line:
  enabled: false
  
llm:
  enabled: false

# テスト時はTTS無効
tts:
  enabled: false 